"""
Field-level OCR accuracy for services/receipt.scan_receipt(), measured
against a synthetic golden set (tests/data/receipts/, generated by
generate_receipts.py) since no real photographed receipts exist in the repo.

Requires live Vertex AI credentials — skipped automatically otherwise.
Regenerate the golden set with: python tests/data/generate_receipts.py
"""

from __future__ import annotations

import json
import time
from pathlib import Path

import pytest

from services import receipt as receipt_service
from tests.conftest import skip_without_live_api
from tests.helpers import latency_stats, save_result

RECEIPTS_DIR = Path(__file__).resolve().parent / "data" / "receipts"


def _load_cases():
    gt_path = RECEIPTS_DIR / "ground_truth.json"
    if not gt_path.exists():
        return []
    return json.loads(gt_path.read_text())


CASES = _load_cases()


def _norm(s):
    return (s or "").strip().lower()


def _amount_close(a, b, tol=0.01):
    if a is None or b is None:
        return a == b
    return abs(float(a) - float(b)) <= tol


def _score_items(pred_items, true_items):
    """Order-independent match on (name substring, price, quantity)."""
    if not true_items:
        return 1.0 if not pred_items else 0.0
    matched = 0
    remaining = list(pred_items)
    for t in true_items:
        hit = None
        for p in remaining:
            if _amount_close(p.get("price"), t["price"]) and p.get("quantity", 1) == t.get("quantity", 1):
                hit = p
                break
        if hit is not None:
            matched += 1
            remaining.remove(hit)
    return matched / len(true_items)


@pytest.mark.live_api
@skip_without_live_api()
@pytest.mark.skipif(not CASES, reason="golden set not generated — run tests/data/generate_receipts.py")
def test_receipt_ocr_field_accuracy(live_api_available):
    field_scores = {"is_receipt": [], "merchant": [], "date": [], "total": [], "currency": [], "items": []}
    per_case = []
    latencies = []

    for case in CASES:
        img_path = RECEIPTS_DIR / case["file"]
        gt = case["ground_truth"]
        with open(img_path, "rb") as f:
            image_bytes = f.read()

        t0 = time.perf_counter()
        try:
            extracted = receipt_service.scan_receipt(image_bytes, "image/png")
            is_receipt_pred = True
        except receipt_service.NotAReceiptError:
            extracted = {}
            is_receipt_pred = False
        elapsed = time.perf_counter() - t0
        latencies.append(elapsed)

        is_receipt_correct = is_receipt_pred == gt["is_receipt"]
        field_scores["is_receipt"].append(is_receipt_correct)

        row = {"id": case["id"], "is_receipt_correct": is_receipt_correct, "latency_s": round(elapsed, 3)}

        if gt["is_receipt"]:
            merchant_ok = _norm(gt["merchant"]) in _norm(extracted.get("merchant")) or \
                          _norm(extracted.get("merchant")) in _norm(gt["merchant"])
            date_ok = extracted.get("date") == gt["date"]
            total_ok = _amount_close(extracted.get("total"), gt["total"])
            currency_ok = extracted.get("currency") == gt["currency"]
            items_score = _score_items(extracted.get("items", []), gt["items"])

            field_scores["merchant"].append(merchant_ok)
            field_scores["date"].append(date_ok)
            field_scores["total"].append(total_ok)
            field_scores["currency"].append(currency_ok)
            field_scores["items"].append(items_score)

            row.update({
                "merchant_ok": merchant_ok, "date_ok": date_ok, "total_ok": total_ok,
                "currency_ok": currency_ok, "items_score": round(items_score, 2),
                "predicted": {k: extracted.get(k) for k in ("merchant", "date", "total", "currency")},
                "expected": {k: gt.get(k) for k in ("merchant", "date", "total", "currency")},
            })
        per_case.append(row)

    def rate(key):
        vals = field_scores[key]
        return round(sum(vals) / len(vals), 4) if vals else None

    result = {
        "n_cases": len(CASES),
        "field_accuracy": {k: rate(k) for k in field_scores},
        "latency": latency_stats(latencies),
        "per_case": per_case,
    }
    save_result("receipt_ocr_accuracy", result)
    print("\nReceipt OCR field accuracy:", json.dumps(result["field_accuracy"], indent=2))
    print("Receipt OCR latency:", json.dumps(result["latency"], indent=2))

    # is_receipt gating and merchant/total extraction are the fields that
    # matter most for the product flow (Verify screen pre-fill quality).
    assert result["field_accuracy"]["is_receipt"] >= 0.8
    assert result["field_accuracy"]["total"] >= 0.6
